//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DialogSemiconductor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DialogSemiconductor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Додати.
        /// </summary>
        public static string Btn_AddTemperature {
            get {
                return ResourceManager.GetString("Btn_AddTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Повернення до налаштувань.
        /// </summary>
        public static string Btn_BackToSettings {
            get {
                return ResourceManager.GetString("Btn_BackToSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Видалити температуру.
        /// </summary>
        public static string Btn_DeleteSelectedTemperature {
            get {
                return ResourceManager.GetString("Btn_DeleteSelectedTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Зняти вибір всіх слотів.
        /// </summary>
        public static string Btn_DeselectAllSlots {
            get {
                return ResourceManager.GetString("Btn_DeselectAllSlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Виконати перевірку.
        /// </summary>
        public static string Btn_ExecuteProgramm {
            get {
                return ResourceManager.GetString("Btn_ExecuteProgramm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перемістити температуру донизу.
        /// </summary>
        public static string Btn_MoveDownSelectedTemperature {
            get {
                return ResourceManager.GetString("Btn_MoveDownSelectedTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перемістити температуру угору.
        /// </summary>
        public static string Btn_MoveUpSelectedTemperature {
            get {
                return ResourceManager.GetString("Btn_MoveUpSelectedTemperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Вибрати всі слоти.
        /// </summary>
        public static string Btn_SelectAllSlots {
            get {
                return ResourceManager.GetString("Btn_SelectAllSlots", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Температура.
        /// </summary>
        public static string Field_Temperature {
            get {
                return ResourceManager.GetString("Field_Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перевірка виконана.
        /// </summary>
        public static string MsgInformation_CheckDone {
            get {
                return ResourceManager.GetString("MsgInformation_CheckDone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ви дійсно бажаєте виконати перевірку?.
        /// </summary>
        public static string MsgQuestion_AreYouSureexEcuteCheck {
            get {
                return ResourceManager.GetString("MsgQuestion_AreYouSureexEcuteCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Дійсно закриваємо програму?.
        /// </summary>
        public static string MsgQuestion_ClosingProgramm {
            get {
                return ResourceManager.GetString("MsgQuestion_ClosingProgramm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Перейти до налаштувань?.
        /// </summary>
        public static string MsgQuestion_GoToSettings {
            get {
                return ResourceManager.GetString("MsgQuestion_GoToSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Інформація.
        /// </summary>
        public static string MsqBox_Information {
            get {
                return ResourceManager.GetString("MsqBox_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Питання.
        /// </summary>
        public static string MsqBox_Question {
            get {
                return ResourceManager.GetString("MsqBox_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Тестова программа для DialogSemiconductor.
        /// </summary>
        public static string Title_Programm {
            get {
                return ResourceManager.GetString("Title_Programm", resourceCulture);
            }
        }
    }
}
